### ISSUE TITLE
Styled JSX compiles `:global(.parent) { .child {} }` to not have a global parent

### ISSUE THREAD

**Issue by vpontis** [swc-project/plugins#456]
If you have:

```css
:global(.theme-root) {
  .parent {
    color: green;
  }
}
```

Then it will be compiled to:

```css
.theme-root.jsx .parent.jsx { color: green }
```

But `.theme-root` should not have `jsx` namespace applied since it's a `:global`.
