### ISSUE TITLE
Styled JSX does not properly strip comments

### ISSUE THREAD

**Issue by vpontis** [swc-project/plugins#460]
```css
div {
  mask-image: -webkit-radial-gradient(
    white,
    black
  ); // Fixing a Safari bug where the corners of the polaroid are not rounded properly
}
```

This will not strip the comment and then it'll pass the comment to LightningCSS which will crash.
